# fly.toml for the food-club-dev
app = 'the-food-club-dev'
primary_region = 'ams'

[build]

[https_service]
    internal_port = 3000
    force_https = true
    auto_stop_machines = 'stop'
    auto_start_machines = true
    min_machines_running = 0
    processes = ['app']

[[vm]]
    memory = '1gb'
    cpu_kind = 'shared'
    cpus = 1

# prevent SEO indexing
[env]
NEXT_PUBLIC_ROBOTS_META = "noindex, nofollow"
