app = 'the-food-club'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  [build.args]
    NEXT_PUBLIC_FC_DEV_PASSWORD = "ETA2025"
    NODE_ENV = "production"

[env]
  NODE_ENV = 'production'
  NEXT_PUBLIC_FC_DEV_PASSWORD = "ETA2025"
  # Don't put secrets here - use fly secrets set instead

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/public'